// dis の opname → 「やさしい」モード向けの平易な日本語。
// 未登録の opname は easyOpLabel がそのまま返す（版が変わっても壊れない）。
const EASY_OP_LABELS: Record<string, string> = {
  RESUME: "準備",
  PUSH_NULL: "空き皿を積む",
  LOAD_CONST: "値を積む",
  LOAD_NAME: "名前を読む",
  LOAD_FAST: "変数を読む",
  LOAD_FAST_CHECK: "変数を読む",
  LOAD_GLOBAL: "名前を読む(global)",
  LOAD_DEREF: "変数を読む(closure)",
  LOAD_ATTR: "属性を読む",
  LOAD_METHOD: "メソッドを読む",
  LOAD_SMALL_INT: "小さな整数を積む",
  STORE_NAME: "名前に代入",
  STORE_FAST: "変数に代入",
  STORE_GLOBAL: "代入(global)",
  STORE_SUBSCR: "添字に代入",
  STORE_ATTR: "属性に代入",
  BINARY_OP: "計算する",
  BINARY_SUBSCR: "添字を読む",
  COMPARE_OP: "比較する",
  UNARY_NOT: "否定する",
  UNARY_NEGATIVE: "符号を反転",
  CALL: "呼び出す",
  CALL_FUNCTION_EX: "呼び出す(展開引数)",
  RETURN_VALUE: "値をかえす",
  RETURN_CONST: "値をかえす",
  POP_TOP: "積んだ値を捨てる",
  GET_ITER: "反復子を取り出す",
  FOR_ITER: "次の値を取り出す",
  END_FOR: "くり返し終了",
  JUMP_BACKWARD: "前に戻る",
  JUMP_FORWARD: "先へ進む",
  POP_JUMP_IF_FALSE: "偽なら分岐",
  POP_JUMP_IF_TRUE: "真なら分岐",
  POP_JUMP_IF_NONE: "Noneなら分岐",
  POP_JUMP_IF_NOT_NONE: "Noneでなければ分岐",
  MAKE_FUNCTION: "関数を作る",
  BUILD_LIST: "リストを作る",
  BUILD_TUPLE: "タプルを作る",
  BUILD_SET: "集合を作る",
  BUILD_MAP: "辞書を作る",
  BUILD_STRING: "文字列を結合",
  FORMAT_VALUE: "値を文字列化",
  UNPACK_SEQUENCE: "分解して代入",
  IMPORT_NAME: "モジュールを読み込む",
  IMPORT_FROM: "名前を取り出す",
  COPY: "値を複製",
  SWAP: "値を入れ替え",
  NOP: "何もしない",
  RAISE_VARARGS: "例外を投げる",
  RERAISE: "例外を再送出",
  PUSH_EXC_INFO: "例外情報を積む",
  CHECK_EXC_MATCH: "例外の型を確認",
  WITH_EXCEPT_START: "with終了処理",
  KW_NAMES: "キーワード引数名",
};

export function easyOpLabel(opname: string): string {
  return EASY_OP_LABELS[opname] ?? opname;
}
