import type { AstNode } from "@/shared/api";

// ast モジュールのノード型名 → 「やさしい」モード向けの平易な日本語。
// 未登録の型は node.type をそのまま表示する。
const EASY_LABELS: Record<string, string> = {
  Module: "プログラム全体",
  Interactive: "対話入力",
  Expression: "式",
  FunctionDef: "関数の定義",
  AsyncFunctionDef: "関数の定義(async)",
  ClassDef: "クラスの定義",
  Return: "かえす",
  Delete: "消す",
  Assign: "代入",
  AugAssign: "複合代入",
  AnnAssign: "型つき代入",
  For: "くり返し(for)",
  AsyncFor: "くり返し(async for)",
  While: "くり返し(while)",
  If: "もし〜なら",
  With: "with文",
  AsyncWith: "with文(async)",
  Raise: "例外を投げる",
  Try: "例外処理",
  TryStar: "例外処理(except*)",
  Assert: "確認する(assert)",
  Import: "読み込み(import)",
  ImportFrom: "読み込み(from import)",
  Global: "global宣言",
  Nonlocal: "nonlocal宣言",
  Expr: "式文",
  Pass: "なにもしない",
  Break: "くり返しを抜ける",
  Continue: "つぎのくり返しへ",
  BoolOp: "論理演算",
  BinOp: "計算",
  UnaryOp: "単項演算",
  Lambda: "無名関数",
  IfExp: "三項式",
  Dict: "辞書",
  Set: "集合",
  ListComp: "リスト内包表記",
  SetComp: "集合内包表記",
  DictComp: "辞書内包表記",
  GeneratorExp: "ジェネレータ式",
  Await: "待つ(await)",
  Yield: "生成する(yield)",
  YieldFrom: "生成する(yield from)",
  Compare: "くらべる",
  Call: "呼び出し",
  FormattedValue: "埋め込み値",
  JoinedStr: "f文字列",
  Constant: "あたい",
  Attribute: "属性アクセス",
  Subscript: "添字アクセス",
  Starred: "アンパック(*)",
  Name: "なまえ",
  List: "リスト",
  Tuple: "タプル",
  Slice: "スライス",
};

export function astEasyLabel(node: AstNode): string {
  return EASY_LABELS[node.type] ?? node.type;
}
